variables:
- group: common

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: '$(ServiceConnectionName)'
    scriptType: 'pscore'
    scriptLocation: 'scriptPath'
    scriptPath: 'scripts/build-and-push.ps1'
    arguments: '-registryName gearoff -repositoryName client -tagName $(Build.BuildId) -buildContextPath $(Build.SourcesDirectory)/client'