steps:
variables:
- group: common
- task: AzureCLI@2
  inputs:
    azureSubscription: '$(ServiceConnectionName)'
    scriptType: 'pscore'
    scriptLocation: 'scriptPath'
    scriptPath: 'infra/deploy-common-infra.ps1'
    arguments: ''